# Generated by Django 6.0 on 2026-01-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_accountbalance_cabinet_personaldata_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='powerbi_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка Power BI'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='powerbi_login',
            field=models.CharField(blank=True, max_length=200, verbose_name='Логин Power BI'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='powerbi_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Пароль Power BI'),
        ),
    ]
