# Generated by Django 6.0 on 2026-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_personaldata_powerbi_link_personaldata_powerbi_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее прочтение пользователем'),
        ),
    ]
