# Generated by Django 6.0 on 2026-01-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_add_last_read_at_to_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_admin_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее прочтение администратором'),
        ),
    ]
