# Generated by Django 6.0

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKIdLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_user_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID пользователя VK')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vk_id_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привязка VK ID',
                'verbose_name_plural': 'Привязки VK ID',
            },
        ),
    ]
