# Generated by Django 6.0 on 2025-12-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL-слаг')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный контент статьи (HTML)')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('reading_time', models.IntegerField(verbose_name='Время чтения в минутах')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('meta_title', models.CharField(blank=True, max_length=300, verbose_name='SEO заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='SEO описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_posts', to='blog.blogpost', verbose_name='Основная статья')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_posts', to='blog.blogpost', verbose_name='Связанная статья')),
            ],
            options={
                'verbose_name': 'Связанная статья',
                'verbose_name_plural': 'Связанные статьи',
                'ordering': ['post', 'order'],
                'unique_together': {('post', 'related_post')},
            },
        ),
    ]
