# Generated by Django 6.0 on 2025-12-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon_svg', models.TextField(blank=True, null=True, verbose_name='SVG иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=20, verbose_name='КПП')),
                ('bik', models.CharField(max_length=20, verbose_name='БИК')),
                ('account_number', models.CharField(max_length=50, verbose_name='Расчетный счет')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Название банка')),
                ('legal_address', models.CharField(max_length=300, verbose_name='Юридический адрес')),
                ('office_address', models.CharField(blank=True, max_length=300, verbose_name='Адрес офиса')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email_sales', models.EmailField(max_length=254, verbose_name='Email для продаж')),
                ('email_support', models.EmailField(max_length=254, verbose_name='Email поддержки')),
                ('email_hr', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email HR')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('viber_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Viber')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на ВКонтакте')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Рабочие часы')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка с формы контактов',
                'verbose_name_plural': 'Заявки с формы контактов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_expanded', models.BooleanField(default=False, verbose_name='Открыт по умолчанию')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon_svg', models.TextField(blank=True, null=True, verbose_name='SVG иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Тип продавца',
                'verbose_name_plural': 'Типы продавцов',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Номер шага')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_tag', models.CharField(max_length=50, verbose_name='Метка времени (например, "5 минут")')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='Список пунктов')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Шаг процесса',
                'verbose_name_plural': 'Шаги процесса',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='SchemeFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Номер шага')),
                ('tag', models.CharField(max_length=100, verbose_name='Тег (например, "Подключение")')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Шаг схемы взаимодействия',
                'verbose_name_plural': 'Схема взаимодействия',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='SocialProofMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Метка (например, "Клиенты")')),
                ('value', models.CharField(max_length=50, verbose_name='Значение (например, "3000+")')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
                'ordering': ['order', 'label'],
            },
        ),
    ]
