# Generated by Django 6.0 on 2025-12-20 18:31

import os
from pathlib import Path
from django.core.files.base import ContentFile
from django.db import migrations, models
from django.conf import settings


def convert_svg_to_files(apps, schema_editor):
    """Конвертирует SVG-коды из icon_svg в файлы изображений"""
    Benefit = apps.get_model('content', 'Benefit')
    
    # Создаем директорию для иконок, если её нет
    icons_dir = Path(settings.MEDIA_ROOT) / 'benefits' / 'icons'
    icons_dir.mkdir(parents=True, exist_ok=True)
    
    # Обрабатываем все преимущества
    for benefit in Benefit.objects.exclude(icon_svg__isnull=True).exclude(icon_svg=''):
        if benefit.icon_svg:
            # Создаем имя файла на основе ID и заголовка
            # Убираем недопустимые символы для имени файла
            safe_title = "".join(c for c in benefit.title if c.isalnum() or c in (' ', '-', '_')).strip()
            safe_title = safe_title.replace(' ', '_')
            filename = f"benefit_{benefit.id}_{safe_title}.svg"
            
            # Сохраняем SVG-код в файл через Django FileField
            svg_content = benefit.icon_svg.encode('utf-8')
            benefit.icon_image.save(
                filename,
                ContentFile(svg_content),
                save=True
            )


def reverse_conversion(apps, schema_editor):
    """Обратная миграция: конвертирует файлы обратно в SVG-коды"""
    Benefit = apps.get_model('content', 'Benefit')
    
    for benefit in Benefit.objects.exclude(icon_image__isnull=True):
        if benefit.icon_image and benefit.icon_image.name:
            filepath = Path(settings.MEDIA_ROOT) / benefit.icon_image.name
            
            if filepath.exists():
                with open(filepath, 'r', encoding='utf-8') as f:
                    benefit.icon_svg = f.read()
                    benefit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        # Шаг 1: Добавляем новое поле icon_image (пока nullable)
        migrations.AddField(
            model_name='benefit',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='benefits/icons/', verbose_name='Иконка'),
        ),
        # Шаг 2: Конвертируем данные
        migrations.RunPython(convert_svg_to_files, reverse_conversion),
        # Шаг 3: Удаляем старое поле icon_svg
        migrations.RemoveField(
            model_name='benefit',
            name='icon_svg',
        ),
    ]
